# This job automatically published a new version to npm at midnight if changes were done.
name: autopublish

on:
  schedule:
    - cron: '0 0 * * *' # run at midnight
  workflow_dispatch: 

jobs:
  auto-publish:
    name: 'Publish nightly on changes'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
        # Bump version
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'qubetools/gh-action-adv-bump-version@v2.0.0'
        with:
          bump-policy: 'all'
          major-wording: 'major,Major,breaking,Breaking'
          minor-wording: 'minor,Minor,new,New,feat,Feat,feature,Feature,release,Release'
          patch-wording: 'fix,Fix,fixes,Fixes,patch,Patch' # Providing patch-wording will override commits defaulting to a patch bump.
          tag-prefix: 'v'
          hours-to-go-back: 24
          skip-if-no-commits: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Log new version number'
        if: steps.version-bump.outputs.bumped == 'true'
        env:
          NEW_VERSION: ${{ steps.version-bump.outputs.newVersion }}
        run: echo "new version $NEW_VERSION"
        # Publish new version to npm
      - uses: actions/setup-node@v2
        if: steps.version-bump.outputs.bumped == 'true'
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        if: steps.version-bump.outputs.bumped == 'true'
      #- name: 'Publish to npm'  
      #  run: npm publish --access=public
      #  if: steps.version-bump.outputs.bumped == 'true'
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
